name: "drand draw"
description: "Draw items from a file using drand"
author: "drand.love"
branding:
  icon: upload-cloud
  color: green
inputs:
  inputDir:
    description: "The directory of files you wish to choose randomly from."
    required: false
    default: "."
  outputDir:
    description: "The directory where you wish the randomly selected output to go."
    required: false
    default: "."
  outputPrefix:
    description: "Files in the `outputDir` will be prefixed with this. Useful so you don't overwrite files if you're using the same directory for input and output.. The default is `draw-`"
    required: false
    default: "draw-"
  drandURL:
    description: "The drand endpoint you wish to use for the draw. The default is `https://api.drand.sh`"
    required: false
    default: "https://api.drand.sh"
runs:
  using: "node16"
  main: "index.js"